package com.kira.farm_fresh_store.utils.enums;

public enum Status {
    ACTIVE, INACTIVE, ONSALE, WAITING, PACKAGING, DELIVERING, RECEIVED, APPROVED, DENIED, WORKING,
    CUSTOMERCANCELED, STAFFCANCELED, DONE, SIGNED, NEW, SUCCESS, FAIL, CONFIRMING,MISSED,PENDING
}
